github: [PREETCHAUHAN]
patreon: DJ Preet
custom: ["https://www.paypal.me/djpreet"]
paytm: [preet.6@paytm]
buy_me_a_coffee: ["https://buymeacoffee.com/djpreet3215"]
ko_fi: ["https://ko-fi.com/djpreet"]
